### ISSUE TITLE
Ampersand symbol(&) causes an error when converted into mm

### ISSUE THREAD

**Issue by jooyoungseo** [pzhaonet/mindr#10]
Hello,

If you convert any md file that contains ampersand symbol (&) into mm, the created mm file is not open properly in any mindmap clients.

I have also attempted to switch the symbol to amp; in the original md file, but it is not translated back into ampersand (&) in the mm file.

Would you mind resolving this issue?

**Comment by pzhaonet** [comment]
The new version 1.1.3 has solved this problem. Thanks for your feedback,
