### ISSUE TITLE
Is it possible to output the md mm or rmd to a html format with some javascript ?

### ISSUE THREAD

**Issue by ghost** [pzhaonet/mindr#11]
Hello Zhao thank you for making this available ! I'm just wondering if you are planning to add a html output because I think it would be great to share the mm on web. Maybe you will say that it suffices to convert the mm to png but in this case some rich-text features such as hyperlink (a feature that you'll add based on your reponse to an issue) would be lost.

Tks again !

**Comment by VerenaHeld** [comment]
@ghost, not sure if it helps, but in RStudio you can simply get HTML Output:
Create an interactive mind map with `markmap()`.
`Viewer` > `Export` > `Save as Web Page...`

**Comment by pzhaonet** [comment]
Now the newest version 1.2.0 can save the mind map as an HTML widget file. Please see the help of `mm()`.
