### ISSUE TITLE
Add filter for file types

### ISSUE THREAD

**Issue by wuffi** [pzhaonet/mindr#12]
Thanks a lot for making the *mindr* package available. I like the idea a lot.  
The `outline()` function looks for files with any extension in a given directory, which can cause problems, if there are other files than `.Rmd` or `.md`.
My `.Rmd` files are located in a directory, which also contains PDF and other files, which also contain lines starting with `#`. This in turn causes the function call to `strsplit()` in the `md2mm()` function to crash.
To avoid this problem, it might be a good idea to add an additional (optional) option to the `md2mm()` function to filter for files with a certain extension, like, for example `.Rmd` or `.md`.

**Comment by pzhaonet** [comment]
This is a very good idea. Thank you very much.

**Comment by pzhaonet** [comment]
The new version 1.1.3 now supports the filter. Please update it and see the help.
