### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ppernot** [pzhaonet/mindr#13]
Hi, great package !

Would it be possible to include clickable links in the nodes of a markmap widget ?
I tried to insert markdown links, but they are converted into simple text...

Thanks

Pascal

**Comment by pzhaonet** [comment]
Hi! mindr supports links when converting markdown files into .mm files, which can be viewed by most of popular mind map software. The markmap widget in mindr is based on the javascript component [markmap]( https://github.com/dundalek/markmap), which seems no support for links in the text. If you have this need, it might be a good practice to open an issue to the [markmap javascript](https://github.com/dundalek/markmap), 

Thank you for your question.

**Comment by ppernot** [comment]
OK, thanks
