### ISSUE TITLE
mm2md: allow max.level arg

### ISSUE THREAD

**Issue by friendly** [pzhaonet/mindr#16]
For more general use, in `md2mm` you should at  least allow a `max.level` argument to select the maximum level in markdown files that will be shown in the mindmap.

max.level = 1: show only chapter level
max.level = 2: show only chapter/section level
...

**Comment by pzhaonet** [comment]
Good suggestion! I will keep it in mind. Thanks!

**Comment by pzhaonet** [comment]
The new development version 1.3.1  supports the maximum level.
