### ISSUE TITLE
How to apply 'mindr' in R shiny

### ISSUE THREAD

**Issue by 01miaom** [pzhaonet/mindr#18]
I try to embed the mind into shiny webpage, but it return an error that the parameter length is zero.
(Can be used normally in R studio)
code: 
>library('miner')

...

> input <- system.file("xuer.md", package = "mindr"),
>                               mm(from = input, type = "file", root = "Ins", to = "learningr.mm"),

...

**Comment by 01miaom** [comment]
sorry, is mindr, computer automatically corrects spelling.

**Comment by pzhaonet** [comment]
You can save the mind map as a html widget and embed it into a shiny app.

```
library(mindr)
input <- system.file('examples/r/rmd2r.Rmd', package = 'mindr')
mm(from = input, type = 'file', root = 'mindr', widget_name = "test.html")

library(shiny)
ui <- fluidPage(
  includeHTML("test.html")
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by 01miaom** [comment]
Thx~
This gave me a good idea to solve similar questions.
Actually, I have been worrying about how to insert interactive pictures to shiny for a long time.
