### ISSUE TITLE
outline() usage

### ISSUE THREAD

**Issue by zq2323** [pzhaonet/mindr#19]
Thank you for developing such an amazing tool!
I have a question about the function outline(). When running outline(),  There just is an outline.md file got in the working directory.  How can I get the outline plot with the outline() function? Thanks!
![image](https://user-images.githubusercontent.com/23326363/108932840-ff8b1e00-7684-11eb-968a-8046eb8d248e.png)

**Comment by pzhaonet** [comment]
No, you cannot get a plot with it. It is only used for getting the outline in text.
