### ISSUE TITLE
How can I set layout options other than 'tree'?

### ISSUE THREAD

**Issue by pbrazda** [pzhaonet/mindr#22]
How can I set layout options other than 'tree'?
Like the "Mindmap of blogdown manual"  in [this manual](https://mran.microsoft.com/snapshot/2017-07-07/web/packages/mindr/vignettes/mindr.html)?

Thank you!

**Comment by pzhaonet** [comment]
You can open the .mm file with a third-party software package like freemind or xmind and set the layout there.
