### ISSUE TITLE
Problem with a simple md file

### ISSUE THREAD

**Issue by sdasgup3** [pzhaonet/mindr#3]
I am having problem lifting  the following md snippet to mm format. The error I am getting is
```
Error in if (diffncc[i] == 1) mm[i + 2] <- paste0("<node TEXT=\"", mmtext[i],  : 
  missing value where TRUE/FALSE needed
```

# A
  - B
    - C
  - D
    - E
    - F

**Comment by pzhaonet** [comment]
Please try writing your md like this:

```
## A
### B
#### C
### D
#### E
#### F
```

The reason is that mindr retrieves the structure of the mind map from the titles and subtitles of sections.
