### ISSUE TITLE
collapsed child nodes at start

### ISSUE THREAD

**Issue by germayneng** [pzhaonet/mindr#4]
Hi there,

Thanks for the wonderful package. anyway to start with the child nodes collapsed ? ( with markmap function)

**Comment by pzhaonet** [comment]
Sorry I do not get your point. Could you provide a mini example which shows your problem?

**Comment by germayneng** [comment]
for example 

# parent 
## child 
## child 
## child 

possible to plot the mind map with the child nodes collapsed? The default mind map starts with 


               - child 
parent -o- child 
               - child 

i want:

parent -o

**Comment by germayneng** [comment]
it starts out like this 
![2](https://user-images.githubusercontent.com/22788747/31603609-4370f00e-b293-11e7-800b-7fa225eab250.JPG)


Can i start out with the nodes collapsed?
![1](https://user-images.githubusercontent.com/22788747/31603595-3d2cb746-b293-11e7-9ebf-6150ab907fc1.JPG)

**Comment by pzhaonet** [comment]
I see. You have to click the circle of the node to expand or collapse. By default the child nodes are expanded. The JavaScript library of [markmap](https://github.com/dundalek/markmap) might have the option, but I did not find it.

**Comment by germayneng** [comment]
so currently there is no way to start collapsed ? 

if so, thank you for your reply :)

**Comment by pzhaonet** [comment]
I will keep an eye on it. If there is, I will let you know. Thank you for your comments!
