### ISSUE TITLE
Will support inline Latex formula?

### ISSUE THREAD

**Issue by specter119** [pzhaonet/mindr#5]
It seems that Latex formula will display as origin text, will support the conversion of Latex formula in the future?

**Comment by pzhaonet** [comment]
The answer is unfortunately no. mindr only processes plain text. If you want instert LaTeX formula in a mindmap, I would suggest docear.

**Comment by specter119** [comment]
@pzhaonet Thanks, but Docear can not even launch on recent macOS.

**Comment by pzhaonet** [comment]
@specter119 The DocEar team wrote [a post](https://www.scss.tcd.ie/joeran.beel/blog/2017/02/05/docears-online-services-are-down-recommendation-user-registration-backup/) last year, saying

> Please note that for the foreseeable future we will not continue the development of Docear as we have not enough funding and time.

Although DocEar is available for MacOS, it has not been updated for a long time. Luckily it is [open-source](https://github.com/BeelGroup/Docear-Desktop).

Anyway, I updated mindr and now it can support LaTeX equations if the mindmap is displayed in DocEar.
