### ISSUE TITLE
Radial mind map rather than tree?

### ISSUE THREAD

**Issue by lbramley** [pzhaonet/mindr#6]
Hi,

Currently the only option that seems to be available is a tree layout - if you want a radial mind map (like your Chinese-language Learning R example), it seems it has to be opened in e.g. xMind. Is this accurate? Do you plan to add a "traditional" mind map layout option like this at any point? (I want to incorporate a mind map into a shiny app, so it doesn't make sense to force the user to go to another piece of software to get the result.)

**Comment by pzhaonet** [comment]
You are right. Currently the radial layout is not available. It is a very good idea to add other layouts to mindr. I will leave it open to the future plan. Thank you for your message!

**Comment by jdonnell01** [comment]
Hi @pzhaonet I would love this feature as well in addition to the ability to include hyperlinks for certain nodes.
