### ISSUE TITLE
markmap only shows a root node

### ISSUE THREAD

**Issue by askhari139** [pzhaonet/mindr#8]
Hi,

The example in the wiki works fine. But when I try to use the markmap function with an mm file I created does not work (I put the file in the mm folder in the working directory as directed). I tried to copy the mm file generated in the example to the mm folder in working directory but that isn't working either. Please help me out.

**Comment by pzhaonet** [comment]
Thanks for the feedback. The function `markup()` creates a mindmap from a markdown file, NOT an mm file. If you want to display an mm file with `markup()`, you could use the `mm2md()` function to convert your mm file into markdown, and display it with `markup()`.

**Comment by pzhaonet** [comment]
Now the feature of displaying a .mm file is available. Put the .mm file into a folder and run:

```
markmap(input = '.mm', folder = 'mm')
```
