### ISSUE TITLE
Mindmap labels with link to URL

### ISSUE THREAD

**Issue by instantkaffee** [pzhaonet/mindr#9]
I want to create a mindmap from markdown.
How can I ensure that the mind map node label reacts on clicking containing a link to a URL?

**Comment by pzhaonet** [comment]
The current version does not support hyperlinks yet. I will add this feature in the new version soon. Thanks for the suggestion!

**Comment by ghost** [comment]
@pzhaonet It would be very nice ! Looking forward to this feature eagerly.

**Comment by pzhaonet** [comment]
The new version has this feature now.
